name: XCode Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build the default scheme for macOS
    runs-on: macos-latest
    defaults:
      run:
        working-directory: TextAdventure

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
          
      - name: Show the currently detailed version of Xcode for CLI
        run: xcode-select -p
          
      - name: Build
        env:
          project: ${{ 'TextAdventure.xcodeproj' }}
          scheme: ${{ 'default' }}
        run: xcodebuild clean test -project "$project" -scheme "$scheme" 
